version: '3.9'
services:
  postgres:
    container_name: ${POSTGRES_DB}-postgres
    image: postgres:13.3-alpine
    restart: always
    volumes:
      - ${POSTGRES_DATA_DIR}:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}      
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"   
 
  dev:
    container_name: students_api
    image: nestjs-api-dev:1.0.0
    build:
        context: .        
        dockerfile: ./Dockerfile
    ports:      
      - 4000:4000
      

    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    
  dev-app:
    container_name: students_app
    image: nextjs-app-dev:1.0.0
    build:
        context: .        
        dockerfile: ./app/Dockerfile
    ports:      
      - 3000:3000
    

    environment:
      NEXT_APP_API_ROUTE: http://students_api:4000/graphql
    
    volumes:
      - .:/usr/app
      - /usr/app/node_modules

    

  
     
networks:
  default:
    external:
      name: ${DOCKER_NETWORK}